[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 100
target-version = "py311"


[tool.ruff.lint]
select = ["E","F","I","B","UP","SIM"]
ignore = ["E203","B008"]
