[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["legiontrap"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","W","UP","B"]
ignore = []
exclude = ["ui/frontend","node_modules",".venv"]
fix = true
