[pytest]
pythonpath = .
env =
  PRIVACY_MODE=false
  FEED_SALT=testsalt
  API_KEY=dev-123
  JWT_SECRET=test-jwt-secret-do-not-use
  DASH_PASS=$2b$12$G6FRFvRadOZ6ztbYn34DzOQZswMD5T9DByiQrKh4dADcvwvv5mAxC
