"""
ATT&CK Navigator layer builder for LegionTrap TI.

Pure transformation module: receives plain Python dicts from the repository
layer and returns a Navigator layer dict ready for JSON serialisation.

No FastAPI, SQLAlchemy, or settings imports.
"""

from __future__ import annotations

from datetime import UTC, datetime

# Maps ATT&CK tactic display names (as stored in event_types.attack_tactic)
# to the kebab-case tactic IDs expected by the Navigator layer format.
_TACTIC_SLUGS: dict[str, str] = {
    "Collection": "collection",
    "Command and Control": "command-and-control",
    "Credential Access": "credential-access",
    "Defense Evasion": "defense-evasion",
    "Discovery": "discovery",
    "Execution": "execution",
    "Exfiltration": "exfiltration",
    "Impact": "impact",
    "Initial Access": "initial-access",
    "Lateral Movement": "lateral-movement",
    "Persistence": "persistence",
    "Privilege Escalation": "privilege-escalation",
    "Reconnaissance": "reconnaissance",
    "Resource Development": "resource-development",
}


def _tactic_slug(tactic_name: str | None) -> str | None:
    """Convert an ATT&CK tactic display name to a Navigator kebab-case slug."""
    if not tactic_name:
        return None
    return _TACTIC_SLUGS.get(tactic_name, tactic_name.lower().replace(" ", "-"))


def build_navigator_layer(
    techniques: list[dict],
    layer_name: str = "LegionTrap TI",
    description: str = "",
) -> dict:
    """
    Build an ATT&CK Navigator layer dict from aggregated technique count rows.

    Args:
        techniques: list of dicts with keys:
            attack_tactic   (str | None)  — tactic display name from event_types
            attack_technique (str | None) — technique ID, e.g. "T1110.001"
            label           (str)         — human-readable event type label
            event_count     (int)         — total events observed for this technique
        layer_name: display name for the Navigator layer tab
        description: optional layer description; defaults to a generated timestamp

    Returns:
        Navigator layer dict. Caller serialises with json.dumps().
    """
    now = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    max_score = max((t.get("event_count", 0) for t in techniques), default=1)

    technique_entries: list[dict] = []
    for t in techniques:
        technique_id = t.get("attack_technique")
        if not technique_id:
            continue

        event_count = t.get("event_count", 0)
        entry: dict = {
            "techniqueID": technique_id,
            "score": event_count,
            "color": "",
            "comment": (f"{event_count} event{'s' if event_count != 1 else ''} observed"),
            "enabled": True,
            "showSubtechniques": False,
            "metadata": [
                {"name": "event_count", "value": str(event_count)},
                {"name": "event_type_label", "value": t.get("label") or ""},
            ],
        }

        tactic = _tactic_slug(t.get("attack_tactic"))
        if tactic:
            entry["tactic"] = tactic

        technique_entries.append(entry)

    return {
        "name": layer_name,
        "versions": {
            "attack": "16.0",
            "navigator": "4.9.6",
            "layer": "4.5",
        },
        "domain": "enterprise-attack",
        "description": description or f"Generated by LegionTrap TI on {now}",
        "filters": {
            "platforms": ["Linux", "Windows", "macOS", "Network"],
        },
        "sorting": 3,
        "layout": {
            "layout": "side",
            "showID": True,
            "showName": True,
        },
        "hideDisabled": False,
        "techniques": technique_entries,
        "gradient": {
            "colors": ["#ffffff", "#ff9999", "#ff0000"],
            "minValue": 0,
            "maxValue": max_score,
        },
        "legendItems": [],
        "metadata": [
            {"name": "generated_at", "value": now},
            {"name": "source", "value": "LegionTrap TI"},
        ],
        "links": [],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#1a1a2e",
    }
